name: Bug Report
description: 再現手順と環境を明確にしたバグ報告
title: "[Bug]: "
labels: [ "bug", "triage" ]
assignees: []

body:
# ── 基本 ───────────────────────────────────────────────
- type: input
  id: summary
  attributes:
    label: Summary
    description: 50 文字以内で端的に問題を表現
    placeholder: ex. ログイン後 500 エラーが発生
  validations:
    required: true

- type: dropdown
  id: severity
  attributes:
    label: Severity
    description: 影響度
    options:
    - Critical (システム全体停止)
    - Major (主要機能停止)
    - Minor (軽微)
    default: 1
  validations:
    required: true

# ── 再現情報 ───────────────────────────────────────────
- type: textarea
  id: steps
  attributes:
    label: Steps to Reproduce
    description: 再現手順 (1 行 1 ステップ)
    placeholder: |
      1. アプリを起動
      2. ユーザーAでログイン
      3. 「設定」をクリック
    value: |
      1.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    placeholder: ex. ダッシュボードへ遷移する
  validations:
    required: true

- type: textarea
  id: actual
  attributes:
    label: Actual Behavior
    placeholder: ex. 500 Internal Server Error
  validations:
    required: true

# ── 環境情報 ───────────────────────────────────────────
- type: input
  id: app_version
  attributes:
    label: App Version
    placeholder: ex. 1.0.3
  validations:
    required: true

- type: dropdown
  id: os
  attributes:
    label: OS
    options:
    - Windows
    - macOS
    - Linux
    - iOS
    - Android
    - Other
    default: 2
  validations:
    required: true

- type: dropdown
  id: browser
  attributes:
    label: Browser
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Edge
    - N/A (Desktop App)
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Logs
    description: 関連ログ（```不要）。長い場合は Gist でも可
    render: shell

# ── 解決のヒント ──────────────────────────────────────
- type: textarea
  id: suspected_cause
  attributes:
    label: Suspected Cause / Idea
    placeholder: ex. 認証トークンの有効期限切れか？
  validations:
    required: false

# ── タスク ───────────────────────────────────────────
- type: textarea
  id: tasks
  attributes:
    label: Tasks
    description: 本バグ解決に必要な作業をチェックリストで列挙
    placeholder: |
      - [ ] 再現テスト作成
      - [ ] 修正実装
      - [ ] リリースノート更新
    value: |
      - [ ]
  validations:
    required: false

# ── 同意 ────────────────────────────────────────────
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    options:
    - label: 同意します
      required: true
